# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 02:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playername', models.CharField(max_length=50)),
                ('begin_chip', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('round_bet', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('accum_bet', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('card_one', models.CharField(max_length=10)),
                ('card_two', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
