# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 04:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0002_auto_20171024_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='hand_card',
        ),
    ]
