# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0003_remove_player_hand_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='user',
        ),
        migrations.RemoveField(
            model_name='game',
            name='players',
        ),
        migrations.AlterField(
            model_name='game',
            name='pot_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='round_max_bet',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='round_status',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
