# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 17:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poker', '0004_auto_20171025_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playername', models.CharField(max_length=50)),
                ('begin_chip', models.IntegerField(default=0)),
                ('round_bet', models.IntegerField(default=0)),
                ('accum_bet', models.IntegerField(default=0)),
                ('card_one', models.CharField(max_length=10)),
                ('card_two', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=10, null=True)),
                ('seat_id', models.PositiveSmallIntegerField(null=True)),
                ('chip_remain', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poker.Game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
