# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0006_auto_20171025_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='bigblind',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='game',
            name='blind',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='game',
            name='buyin',
            field=models.IntegerField(default=600),
        ),
    ]
