# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0010_auto_20171105_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
