# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0011_player_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='num_start',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='card_one',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='card_two',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
