# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0013_game_is_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='current_player',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='dealer',
            field=models.SmallIntegerField(default=-1, null=True),
        ),
    ]
