# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0014_auto_20171118_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_round_play',
            field=models.BooleanField(default=False),
        ),
    ]
